Repository today-focus/today-focus, pull requests merged in 2022-09, with the labels that each got.

#1 📝 docs: create pull_request_template.md
  .github/pull_request_template.md
Labels: documentation

#3 ➕ chore: set up tsconfig
  .eslintignore
  .eslintrc.json
  jest.config.js
  package.json
  tsconfig.json
  yarn.lock
Labels: enhancement

#5 ✨ feat: set up splash screen and app icon
  app.json
  assets/adaptive-icon.png
  assets/favicon.png
  assets/icon.png
  assets/splash.png
  src/assets/adaptive-icon.png
  src/assets/favicon.png
  src/assets/icon.png
  src/assets/splash.png
Labels: enhancement

#6 ✨ feat: implement current date
  package-lock.json
  package.json
  src/screens/MainScreen.tsx
  yarn.lock
Labels: enhancement

#10 ✨ feat: implement todolist text input and save method
  src/components/TodoItem.tsx
  src/components/TodoList.tsx
  src/screens/MainScreen.tsx
Labels: enhancement

#12 ✨ feat: implement checkbox save and remove method from asyncstorage
  src/components/TodoItem.tsx
  src/components/TodoList.tsx
Labels: enhancement

#14 ✨ feat: implement todoitem delete method
  src/components/TodoItem.tsx
  src/components/TodoList.tsx
Labels: enhancement

#18 ✨ feat: implement routine component
  src/components/Carousel.tsx
  src/components/RenderModal.tsx
  src/components/Routine.tsx
  src/components/RoutineTodoList.tsx
  src/screens/MainScreen.tsx
Labels: enhancement

#19 🐛 fix: modify todo item to be saved even when it has no text
  src/components/TodoItem.tsx
  src/components/TodoList.tsx
Labels: bug
